### ISSUE TITLE
Mention dependency on Boost

### ISSUE THREAD

**Issue by martinmoene** [viboes/GSL#1]
Hi Vicente,

Good to see another implementation for GSL coming.

I think it might be of interest to potential users of the C++98 fork that it depends on Boost.

cheers,
Martin

**Comment by viboes** [comment]
Hi Martin, I heard that you have also an implementation of GSL that works for C++98/C++03/C++11. I'll take a deep look very soon.

Yes, I will add the dependency. Glad to see that your documentation has references to other implementations and a comparison of the provided features by each library.

**Comment by martinmoene** [comment]
Thanks for reminding, I've added your version to the list.
Note that my feature comparison is not entirely up-to-date.

**Comment by viboes** [comment]
Yes, I should just report the features I support.

Thanks for the addition.

Mention added on the cxx98 branch as the master branch don't depends on Boost.

https://github.com/viboes/GSL/commit/25350bac47229bbbb0ea99171ea76f74aa14e7e0

**Comment by martinmoene** [comment]
I see you provide [gsl-lite-vc6.h](https://github.com/viboes/GSL/blob/cxx98/include/gsl/gsl-lite-vc6.h). IIRC it still needs some work, however as I don't have to to use VC6 anymore my self, there's less motivation to invest much time).

**Comment by viboes** [comment]
I don't understand. What do you mean by gsl-lite-vc6.h?

**Comment by martinmoene** [comment]
Ah, it's linked from the table [Reported to work with](https://github.com/viboes/GSL/tree/cxx98#reported-to-work-with), but the file is not not present. The mention of _6 (6) via header gsl-lite-vc6.h_ should be removed.

**Comment by viboes** [comment]
Done.
